http:
  middlewares:
    sablier-middleware:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          duration: 10m
          # Configuración adicional (opcional):
          # names: whoami
          # session: true
          # showDetails: true
  
