services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--accesslog=true"
      - "--accesslog.filepath=/dev/stdout"
      - "--accesslog.format=json"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.middlewares.req-headers.headers.customrequestheaders.X-Request-ID=requestid"
      - "traefik.http.middlewares.req-headers.headers.customrequestheaders.X-Trace-Time=responsetime"
      - "traefik.http.middlewares.test-auth.basicauth.users=alex:$$2y$$05$$pEfyQFy5gONDUHId6qvbz.WHha5CP8mMtS.FISGnjH.FpaIV8Kju2"
      - "traefik.http.middlewares.error-pages.errors.status=404-500"
      - "traefik.http.middlewares.error-pages.errors.service=nginx"
      - "traefik.http.middlewares.error-pages.errors.query=/error.html"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.middlewares=test-auth,req-headers"

  backend:
    build:
      context: ./backend
    container_name: node-backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.middlewares=test-auth,req-headers,error-pages"

  backend-replica-1:
    build:
      context: ./backend
    container_name: node-backend-replica-1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-replica-1.rule=Host(`api.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend-replica-1.middlewares=test-auth,req-headers,error-pages"

  backend-replica-2:
    build:
      context: ./backend
    container_name: node-backend-replica-2
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-replica-2.rule=Host(`api.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend-replica-2.middlewares=test-auth,req-headers,error-pages"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

volumes:
  grafana-data: