# Middleware globales
http:
  middlewares:
    req-headers:
      headers:
        customRequestHeaders:
          X-Request-ID: "requestid"
          X-Trace-Time: "responsetime"
    test-auth:
      basicAuth:
        users:
          - "alex:$2y$05$pEfyQFy5gONDUHId6qvbz.WHha5CP8mMtS.FISGnjH.FpaIV8Kju2"
    error-pages:
      errors:
        status: ["404-500"]
        service: "nginx@docker"
        query: "/error.html"
    # Middleware para acceso a /admin solo desde IPs específicas
    admin-whitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.1.0/24"  # Ejemplo: rango de IPs locales permitidas
          - "10.0.0.1"        # Ejemplo: IP específica permitida
    
    # Middleware para detectar si el usuario está autenticado
    authenticated-users:
      chain:
        middlewares:
          - "test-auth@file"  # Usa la autenticación básica existente
          - "auth-marker@file"
    
    # Middleware para marcar usuarios autenticados
    auth-marker:
      headers:
        customRequestHeaders:
          X-User-Authenticated: "true"