entryPoints: 
  web: 
    address: ":80" 
  websecure: 
    address: ":443" 

api:
  insecure: true  # Habilita el dashboard en modo inseguro (solo para pruebas)

providers: 
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false